version: '2'
services:
  docker-compose-eureka:
    image: robin9999/docker-compose-eureka:v1.0.0
    restart: always
    container_name: docker-compose-eureka
    hostname: docker-compose-eureka
    ports:
      - "8761:8761"  
  users-app:
    image: users
    depends_on:
      - docker-compose-eureka
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@docker-compose-eureka:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://users-mysql:3306/users?useUnicode=true&characterEncoding=utf8&useSSL=false'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD=admin

